version: "3.8"

services:
  keycloak:
    container_name: keycloak
    ports:
      - 8080:8080
    networks:
      - services
    image: quay.io/keycloak/keycloak:17.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev

networks:
  services:
    name: Knightly
    external: true